#!/usr/bin/env python3
"""Generate the Stage 3 root cutover: v2 at `/`, v1 preserved at `/v1/`.

    python3 scripts/cutover.py --check    say what would change, write nothing
    python3 scripts/cutover.py --write    do it

Design v2 §10, Stage 3: "Root cutover is a separate commit touching only the entry
point/assets; v1 stays at /v1/ for one release; the legacy export remains. Rollback is
a single revert."

Generated rather than hand-edited so the change is auditable, re-runnable, and
obviously mechanical. Two files are written and nothing else moves:

  index.html      v2's markup, with its asset references rebased from ../ to the root
  v1/index.html   today's root page, with <base href="../"> added

**No JavaScript, CSS or data file moves.** That is the point:

  - v1's runtime stays byte-identical at assets/js/sdv-index.json. The Stage 0 golden
    corpus is pinned to its SHA-256, and Stage 3's whole argument rests on the
    differential still describing the page that is being retired. A single <base>
    element in a COPY of the markup redirects every relative path in it to the root,
    so the shipped v1 behaves exactly as it does today without one byte of its code
    changing.

  - v2's modules stay under v2/assets/. data.js resolves the projection through
    import.meta.url with three levels of ../, which is correct from v2/assets/js/ and
    would silently break if the files were moved up. Referencing them from the root
    page costs nothing and moves nothing.

So the revert really is `git revert` of one commit: restore two files.
"""
import argparse
import difflib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

BANNER = ('<!-- Generated by scripts/cutover.py from {src}. Do not hand-edit; '
          'edit the source and re-run. -->')


def build_root():
    """v2's page, served from the root."""
    s = (ROOT / 'v2/index.html').read_text()
    subs = [
        ('href="../assets/css/style.css"', 'href="assets/css/style.css"'),
        ('href="assets/css/v2.css"', 'href="v2/assets/css/v2.css"'),
        ('href="../assets/img/sdv-logo.svg"', 'href="assets/img/sdv-logo.svg"'),
        ('src="../assets/img/sdv-logo.svg"', 'src="assets/img/sdv-logo.svg"'),
        ('href="../index.html"', 'href="index.html"'),
        ('src="assets/js/main.js"', 'src="v2/assets/js/main.js"'),
    ]
    for a, b in subs:
        if a not in s:
            sys.exit(f'cutover: expected {a!r} in v2/index.html and did not find it')
        s = s.replace(a, b)

    # The preview banner becomes the ordinary footer, pointing at the archived page.
    s = re.sub(
        r'<div class="credits">.*?</div>',
        '<div class="credits">An index of the Synthetic Data Vault ecosystem · '
        'built from data/sdv-index.json · '
        'the previous version is at <a href="v1/">/v1/</a></div>',
        s, count=1, flags=re.S)
    return s.replace('<head>', '<head>\n  ' + BANNER.format(src='v2/index.html'), 1)


def build_v1():
    """Today's root page, archived, with every relative path redirected to the root.

    <base> is the whole mechanism. assets/js/sdv-index.js fetches
    'data/sdv-index.json' relative to the DOCUMENT, which from /v1/ would be
    /v1/data/... and 404. One element fixes every such path at once and leaves the
    runtime untouched -- which matters, because the golden corpus is pinned to that
    file's hash.
    """
    s = (ROOT / 'index.html').read_text()
    if '<base ' in s:
        sys.exit('cutover: index.html already carries a <base>; refusing to guess')
    s = s.replace('<head>',
                  '<head>\n  ' + BANNER.format(src='index.html') +
                  '\n  <!-- Every path below is written relative to the site root, so '
                  'serving this\n       copy from /v1/ needs exactly one redirect and '
                  'no change to the runtime. -->\n  <base href="../">', 1)
    # The footer cannot carry the notice: v1's stampFooter() replaces .credits with
    # the build stamp as soon as build-info.json arrives, so anything written there
    # disappears a second after load. A separate banner the runtime never touches is
    # the only place that survives.
    banner = ('<div class="archived-note" style="background:#fff4e5;border-bottom:'
              '1px solid #e0b070;padding:.6rem 1rem;font:14px/1.4 system-ui,sans-serif;'
              'text-align:center">This is the <strong>previous version</strong> of the '
              'index, kept for one release. The current site is at '
              '<a href="./">the front page</a>.</div>')
    s = s.replace('<body>', '<body>\n' + banner, 1)
    return s


def report(path, new):
    old = path.read_text() if path.exists() else ''
    if old == new:
        print(f'  {path.relative_to(ROOT)}: unchanged')
        return 0
    diff = list(difflib.unified_diff(old.split('\n'), new.split('\n'),
                                     'current', 'after cutover', lineterm='', n=1))
    changed = [l for l in diff if l[:1] in '+-' and l[:3] not in ('---', '+++')]
    print(f'  {path.relative_to(ROOT)}: {len(changed)} line(s) change')
    for line in changed[:14]:
        print(f'      {line[:150]}')
    if len(changed) > 14:
        print(f'      … and {len(changed) - 14} more')
    return 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true')
    a = ap.parse_args()

    root_html, v1_html = build_root(), build_v1()
    targets = [(ROOT / 'index.html', root_html), (ROOT / 'v1/index.html', v1_html)]

    print('cutover: v2 to /, v1 to /v1/\n')
    for path, content in targets:
        report(path, content)
    print('\nnothing else moves: v1 keeps assets/js/sdv-index.js and '
          'assets/css/style.css,\nv2 keeps v2/assets/, and data/ is untouched.')

    if not a.write:
        print('\n(--check only; pass --write to apply)')
        return 0
    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print('\nwritten. Revert with: git revert <this commit>')
    return 0


if __name__ == '__main__':
    sys.exit(main())
