#!/usr/bin/env python3
"""What the §4 search change did to recall, query by query.

    python3 scripts/recall_report.py > docs/perf/search-recall.md

§4 asks for "explicit frozen examples" covering partial words, multiword queries,
punctuation and non-ASCII text, and §8 makes those the documented exceptions in the
differential. An exception list says a state is ALLOWED to differ; it does not say
how, and "allowed to differ" is exactly where a real regression would hide. This
turns the 24 frozen searches into a table a reader can judge.

Both sides come from recorded runs, not from a reimplementation here: v1 from the
Stage 0 corpus, v2 from the same oracle driven against the shipped engine.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
G = ROOT / 'docs/perf/golden'


def main():
    golden = json.loads((G / 'results.json').read_text())['results']
    gids = json.loads((G / 'records.json').read_text())['ids']
    actual = json.loads((G / 'actual-v2.json').read_text())
    aids = actual['ids']
    states = {s['id']: s for s in json.loads((G / 'states.json').read_text())['states']}

    rows = []
    for sid in sorted(states):
        if not (sid.startswith('search-') or 'search' in sid):
            continue
        if sid not in actual['results']:
            continue
        q = states[sid]['titleQuery']
        v1 = {gids[i] for i in golden[sid]['ids']}
        v2 = {aids[i] for i in actual['results'][sid]['ids']}
        rows.append((sid, q, v1, v2))

    print('# Search recall: what the §4 change did\n')
    print('Generated by `scripts/recall_report.py` from two recorded oracle runs — v1')
    print('from the Stage 0 corpus, v2 from the shipped engine. Not recomputed here.\n')
    print('v2 searches title **and** summary by default, by token, with the last word')
    print('matched as a prefix. v1 searched title and summary by contiguous substring.')
    print('So results move in both directions: tokens miss substrings that straddle a')
    print('word boundary, and find words a substring search would only reach if the')
    print('reader typed them contiguously.\n')
    print('| query | v1 | v2 | kept | gained | note |')
    print('| --- | --: | --: | --: | --: | --- |')
    total_v1 = total_kept = 0
    for sid, q, v1, v2 in rows:
        kept, gained = v1 & v2, v2 - v1
        total_v1 += len(v1)
        total_kept += len(kept)
        pct = f'{100 * len(kept) / len(v1):.0f}%' if v1 else '--'
        note = ''
        if not v1 and not v2:
            note = 'no results either way'
        elif len(v2) > len(v1) * 1.2:
            note = 'widened'
        elif len(kept) < len(v1) * 0.7:
            note = '**narrowed**'
        print(f'| `{q}` | {len(v1):,} | {len(v2):,} | {pct} | +{len(gained):,} | {note} |')
    print(f'\nAcross all frozen queries v2 keeps **{100 * total_kept / total_v1:.0f}%** '
          f'of v1\'s results and adds others.\n')

    print('## Where they differ most\n')
    worst = sorted(rows, key=lambda r: (len(r[2] & r[3]) / len(r[2])) if r[2] else 1)[:4]
    for sid, q, v1, v2 in worst:
        lost = sorted(v1 - v2)
        gained = sorted(v2 - v1)
        print(f'**`{q}`** — v1 {len(v1):,}, v2 {len(v2):,}. '
              f'{len(lost):,} dropped, {len(gained):,} added.')
        if lost:
            print(f'  - dropped, e.g. `{lost[0]}`')
        if gained:
            print(f'  - added, e.g. `{gained[0]}`')
        print()
    return 0


if __name__ == '__main__':
    sys.exit(main())
