#!/usr/bin/env python3
"""Mechanically triage the citing works that show no SDV signal.

    python harvest/triage_signals.py

Scans title and abstract of every record in openalex-citations.json for SDV-family
terms. Records with no match are almost always prior-art citations rather than
uses, and there are far too many to read by hand.

This is a keyword scan, not a reading. It therefore writes conservative values:
citation_only at low or medium confidence, with evidence naming the method and a
needs note where an abstract was missing entirely. Anything it marks can be
overridden later by a hand patch carrying "override": true.

Records WITH a signal are left untouched for hand adjudication.

Writes curate/patches/curation-000-triage.jsonl. Run apply_curation.py after.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKS = os.path.join(ROOT, 'data', 'tail', 'openalex-citations.json')
OUT = os.path.join(ROOT, 'curate', 'patches', 'curation-000-triage.jsonl')

TERMS = {
    'sdv': r'\bsdv\b|synthetic data vault',
    'ctgan': r'\bct-?gan\b',
    'tvae': r'\btvae\b',
    'copulagan': r'copula ?gan',
    'gaussiancopula': r'gaussian ?copula',
    'sdmetrics': r'sdmetrics',
    'sdgym': r'sdgym',
    'par': r'parsynthesizer',
    'tgan': r'\btgan\b',
    'deepecho': r'deepecho',
}


def abstract(rec):
    inverted = rec.get('abstract_inverted_index')
    if not inverted:
        return ''
    positions = {}
    for word, indexes in inverted.items():
        for index in indexes:
            positions[index] = word
    return ' '.join(positions[i] for i in sorted(positions))


def main():
    works = json.load(open(WORKS))
    lines, skipped = [], 0
    for rec in works:
        text = f"{rec.get('title') or ''} {abstract(rec)}".lower()
        if any(re.search(pattern, text) for pattern in TERMS.values()):
            skipped += 1
            continue
        has_abstract = bool(rec.get('abstract_inverted_index'))
        patch = {
            'openalex_id': rec['id'].rsplit('/', 1)[-1],
            'uses_sdv': False,
            'integration': 'citation_only',
            'evidence': ('keyword scan of title and abstract found no SDV-family term'
                         if has_abstract else
                         'keyword scan of title only; no abstract indexed'),
            'confidence': 'medium' if has_abstract else 'low',
        }
        if not has_abstract:
            patch['needs'] = 'no abstract indexed; unscreened by anything but the title'
        lines.append(json.dumps(patch, ensure_ascii=False))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as fh:
        fh.write('// Generated by triage_signals.py. Keyword scan, not a reading.\n')
        fh.write('\n'.join(lines) + '\n')
    print(f'{len(lines)} records triaged as citation_only, '
          f'{skipped} left for hand adjudication -> {OUT}')


if __name__ == '__main__':
    main()
